### ISSUE TITLE
2162-0002 crash on atmosphere

### ISSUE THREAD

**Issue by kurthf91** [Kalyvara/NXTheme-CHROMA#1]
Hello, love the theme! Unfortunately whenever I uninstall a game it crashes atmosphere completely with the error 2162-0002 (0x4a2).
Currently using the Red Wine version and on 16.0.2 (AMS 1.5.4), happens after uninstalling any game from the home menu (pressing + on a game, then going into manage software and delete software)

**Comment by Kalyvara** [comment]
Yeah I've just noticed yesterday. I legit don't know why tf it happens but I'll take a closer look. Might be related to animations.

**Comment by kurthf91** [comment]
It does still happen when uninstalling from the settings menu, and if you look closely you can notice it attempting to load the home menu before crashing so you might be right about it being an animation issue.

**Comment by Kalyvara** [comment]
Seems like there's a conflict between the animation that handles transparency when a game is either focused or unfocused, and the menu reloading animation.

It means that until I find a better solution you'll have to settle with the whole games row at full transparency. It really saddens me because it was an important part of Chroma's design, so I hope I'll figure this out.

[chromaRedWine_home_tempfix.zip](https://github.com/Kalyvara/NXTheme-CHROMA/files/12629504/chromaRedWine_home_tempfix.zip)

**Comment by kurthf91** [comment]
Thank you for the fix. This is by far my favorite theme right now so I hope you can solve this problem, good luck!

**Comment by Kalyvara** [comment]
Nevermind, I've actually fixed it lmao

Let me know if this works on your end

And thanks for the compliment :)

[chromaRedWine_v101_home.zip](https://github.com/Kalyvara/NXTheme-CHROMA/files/12633874/chromaRedWine_v101_home.zip)

**Comment by kurthf91** [comment]
It certainly doesn't bother me, thank you.

**Comment by Kalyvara** [comment]
That was tedious but the problem should be totally solved now, including the "Playing" label transparency thing.

The packs have been updated on Themezer https://themezer.net/themes/homemenu/Chroma-Red-Wine-Ed.-home-v1.1-regular-rounded-2dae
